
all: 8logo.png logo.png 8logo_alt.png 8logo_alt_grad.png

8logo.png:
	inkscape -z -e 8logo.png -w 1920 -h 1920 8logo.svg

logo.png:
	inkscape -z -e logo.png -w 1919 -h 647 logo.svg
8logo_alt.png:
	inkscape -z -e 8logo_alt.png -w 1920 -h 1920 8logo_alt.svg
8logo_alt_grad.png:
	inkscape -z -e 8logo_alt_grad.png -w 1920 -h 1920 8logo_alt_grad.svg

